project_id = "default"

[functions.payment-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = true

[functions.cash-payment]
verify_jwt = true

[functions.cash-payment-confirm]
verify_jwt = true

[functions.payment-status]
verify_jwt = true
